//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chaarsu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BARCODE
    {
        public short LOCNO { get; set; }
        public int ITEM_CODE { get; set; }
        public short PACK_CODE { get; set; }
        public string PACK_DESC { get; set; }
        public decimal UNIT { get; set; }
        public bool bDEFAULT { get; set; }
        public string BAR_CODE { get; set; }
        public short BARTYPE { get; set; }
        public decimal UNIT_PRICE { get; set; }
        public decimal DEALER_PRICE1 { get; set; }
        public decimal DEALER_PRICE2 { get; set; }
        public decimal RF_MARGIN { get; set; }
        public int CUSER { get; set; }
        public System.DateTime CDATE { get; set; }
        public int MUSER { get; set; }
        public System.DateTime MDATE { get; set; }
        public bool bRandomDisc { get; set; }
        public System.DateTime DiscStartDate { get; set; }
        public System.DateTime DiscEndDate { get; set; }
        public System.DateTime DiscStartTime { get; set; }
        public System.DateTime DiscEndTime { get; set; }
        public short DISC_TYPE { get; set; }
        public decimal DISC { get; set; }
        public decimal LOYALTY_DISC { get; set; }
        public decimal STAFF_DISC { get; set; }
        public bool IsActive { get; set; }
        public bool NeedsReplication { get; set; }
        public bool NeedsUpdation { get; set; }
        public bool L1P1NeedsUpdation { get; set; }
        public bool L1P2NeedsUpdation { get; set; }
        public bool L1P3NeedsUpdation { get; set; }
        public bool L1P4NeedsUpdation { get; set; }
        public bool L1P5NeedsUpdation { get; set; }
        public bool L1P6NeedsUpdation { get; set; }
        public bool L1P7NeedsUpdation { get; set; }
        public bool L1P8NeedsUpdation { get; set; }
        public bool L1P9NeedsUpdation { get; set; }
        public bool L1P10NeedsUpdation { get; set; }
        public bool L2P1NeedsUpdation { get; set; }
        public bool L2P2NeedsUpdation { get; set; }
        public bool L2P3NeedsUpdation { get; set; }
        public bool L2P4NeedsUpdation { get; set; }
        public bool L2P5NeedsUpdation { get; set; }
        public bool L2P6NeedsUpdation { get; set; }
        public bool L2P7NeedsUpdation { get; set; }
        public bool L2P8NeedsUpdation { get; set; }
        public bool L2P9NeedsUpdation { get; set; }
        public bool L2P10NeedsUpdation { get; set; }
        public bool L0NeedsUpdation { get; set; }
        public bool L1NeedsUpdation { get; set; }
        public bool L2NeedsUpdation { get; set; }
        public bool L3NeedsUpdation { get; set; }
        public bool L3P1NeedsUpdation { get; set; }
        public bool L4NeedsUpdation { get; set; }
        public bool L5NeedsUpdation { get; set; }
        public bool L6NeedsUpdation { get; set; }
        public bool L3P2NeedsUpdation { get; set; }
        public bool L3P3NeedsUpdation { get; set; }
        public bool L3P4NeedsUpdation { get; set; }
        public bool L3P5NeedsUpdation { get; set; }
        public bool L3P6NeedsUpdation { get; set; }
        public bool L4P1NeedsUpdation { get; set; }
        public bool L4P2NeedsUpdation { get; set; }
        public bool L4P3NeedsUpdation { get; set; }
        public bool L4P4NeedsUpdation { get; set; }
        public bool L4P5NeedsUpdation { get; set; }
        public bool L4P6NeedsUpdation { get; set; }
        public bool L5P6NeedsUpdation { get; set; }
        public bool L5P1NeedsUpdation { get; set; }
        public bool L5P2NeedsUpdation { get; set; }
        public bool L5P3NeedsUpdation { get; set; }
        public bool L5P4NeedsUpdation { get; set; }
        public bool L5P5NeedsUpdation { get; set; }
        public bool L6P1NeedsUpdation { get; set; }
        public bool L6P2NeedsUpdation { get; set; }
        public bool L6P3NeedsUpdation { get; set; }
        public bool L6P4NeedsUpdation { get; set; }
        public bool L6P5NeedsUpdation { get; set; }
        public bool L6P6NeedsUpdation { get; set; }
        public bool L7NeedsUpdation { get; set; }
        public bool L7P1NeedsUpdation { get; set; }
        public bool L7P2NeedsUpdation { get; set; }
        public bool L7P3NeedsUpdation { get; set; }
        public bool L7P4NeedsUpdation { get; set; }
        public bool L7P5NeedsUpdation { get; set; }
        public bool L7P6NeedsUpdation { get; set; }
        public bool L8NeedsUpdation { get; set; }
        public bool L9NeedsUpdation { get; set; }
        public bool L10NeedsUpdation { get; set; }
        public bool L11NeedsUpdation { get; set; }
        public bool L12NeedsUpdation { get; set; }
        public bool L8P1NeedsUpdation { get; set; }
        public bool L9P1NeedsUpdation { get; set; }
        public bool L10P1NeedsUpdation { get; set; }
        public bool L11P1NeedsUpdation { get; set; }
        public bool L12P1NeedsUpdation { get; set; }
        public bool L8P2NeedsUpdation { get; set; }
        public bool L8P3NeedsUpdation { get; set; }
    }
}
