//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chaarsu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS000
    {
        public short LOCNO { get; set; }
        public int ITEM_CODE { get; set; }
        public decimal QTY { get; set; }
        public decimal WH_QTY { get; set; }
        public decimal T_QTY { get; set; }
        public decimal MATERIAL_COST { get; set; }
        public decimal INGR_COST { get; set; }
        public decimal PKG_COST { get; set; }
        public decimal LAB_COST { get; set; }
        public decimal OH_COST { get; set; }
        public decimal OTH_COST { get; set; }
        public decimal WASTAGE { get; set; }
        public decimal COST_PRICE1 { get; set; }
        public decimal COST_PRICE2 { get; set; }
        public decimal COST_PRICE3 { get; set; }
        public decimal NET_COST { get; set; }
        public decimal AVG_COST { get; set; }
        public decimal AVG_COST1 { get; set; }
        public decimal AVG_COST2 { get; set; }
        public decimal AVG_COST3 { get; set; }
        public decimal F_PUR_PRICE { get; set; }
        public decimal LAST_PUR_PRICE1 { get; set; }
        public decimal LAST_PUR_PRICE2 { get; set; }
        public decimal LAST_PUR_PRICE3 { get; set; }
        public string LAST_SUPP { get; set; }
        public string LAST_SUPP1 { get; set; }
        public string LAST_SUPP2 { get; set; }
        public byte FLOOR_NO { get; set; }
        public short COUNTER { get; set; }
        public byte SHELF { get; set; }
        public decimal SHELF_QTY { get; set; }
        public decimal SHELF_FACING { get; set; }
        public System.DateTime LSDATE { get; set; }
        public System.DateTime LPDATE { get; set; }
        public bool ALLOW_NEGATIVE { get; set; }
        public decimal AreaCovered { get; set; }
        public decimal MAX_QTY { get; set; }
        public decimal MIN_QTY { get; set; }
        public decimal OP_STOCK { get; set; }
        public decimal OP_STOCK_VAL { get; set; }
        public bool ITEM_STATUS { get; set; }
        public decimal PHY_QTY { get; set; }
        public int STATUS { get; set; }
        public System.DateTime PDATE { get; set; }
        public bool IsActive { get; set; }
        public bool NeedsReplication { get; set; }
        public bool NeedsUpdation { get; set; }
        public bool L1P1NeedsUpdation { get; set; }
        public bool L1P2NeedsUpdation { get; set; }
        public bool L1P3NeedsUpdation { get; set; }
        public bool L1P4NeedsUpdation { get; set; }
        public bool L1P5NeedsUpdation { get; set; }
        public bool L1P6NeedsUpdation { get; set; }
        public bool L1P7NeedsUpdation { get; set; }
        public bool L1P8NeedsUpdation { get; set; }
        public bool L1P9NeedsUpdation { get; set; }
        public bool L1P10NeedsUpdation { get; set; }
        public bool L2P1NeedsUpdation { get; set; }
        public bool L2P2NeedsUpdation { get; set; }
        public bool L2P3NeedsUpdation { get; set; }
        public bool L2P4NeedsUpdation { get; set; }
        public bool L2P5NeedsUpdation { get; set; }
        public bool L2P6NeedsUpdation { get; set; }
        public bool L2P7NeedsUpdation { get; set; }
        public bool L2P8NeedsUpdation { get; set; }
        public bool L2P9NeedsUpdation { get; set; }
        public bool L2P10NeedsUpdation { get; set; }
        public bool L0NeedsUpdation { get; set; }
        public bool L1NeedsUpdation { get; set; }
        public bool L2NeedsUpdation { get; set; }
        public bool L3NeedsUpdation { get; set; }
        public bool L3P1NeedsUpdation { get; set; }
        public bool L4NeedsUpdation { get; set; }
        public bool L5NeedsUpdation { get; set; }
        public bool L6NeedsUpdation { get; set; }
        public bool L3P2NeedsUpdation { get; set; }
        public bool L3P3NeedsUpdation { get; set; }
        public bool L3P4NeedsUpdation { get; set; }
        public bool L3P5NeedsUpdation { get; set; }
        public bool L3P6NeedsUpdation { get; set; }
        public bool L4P1NeedsUpdation { get; set; }
        public bool L4P2NeedsUpdation { get; set; }
        public bool L4P3NeedsUpdation { get; set; }
        public bool L4P4NeedsUpdation { get; set; }
        public bool L4P5NeedsUpdation { get; set; }
        public bool L4P6NeedsUpdation { get; set; }
        public bool L5P6NeedsUpdation { get; set; }
        public bool L5P1NeedsUpdation { get; set; }
        public bool L5P2NeedsUpdation { get; set; }
        public bool L5P3NeedsUpdation { get; set; }
        public bool L5P4NeedsUpdation { get; set; }
        public bool L5P5NeedsUpdation { get; set; }
        public bool L6P1NeedsUpdation { get; set; }
        public bool L6P2NeedsUpdation { get; set; }
        public bool L6P3NeedsUpdation { get; set; }
        public bool L6P4NeedsUpdation { get; set; }
        public bool L6P5NeedsUpdation { get; set; }
        public bool L6P6NeedsUpdation { get; set; }
        public bool L7NeedsUpdation { get; set; }
        public bool L7P1NeedsUpdation { get; set; }
        public bool L7P2NeedsUpdation { get; set; }
        public bool L7P3NeedsUpdation { get; set; }
        public bool L7P4NeedsUpdation { get; set; }
        public bool L7P5NeedsUpdation { get; set; }
        public bool L7P6NeedsUpdation { get; set; }
        public bool L8NeedsUpdation { get; set; }
        public bool L9NeedsUpdation { get; set; }
        public bool L10NeedsUpdation { get; set; }
        public bool L11NeedsUpdation { get; set; }
        public bool L12NeedsUpdation { get; set; }
        public bool L8P1NeedsUpdation { get; set; }
        public bool L9P1NeedsUpdation { get; set; }
        public bool L10P1NeedsUpdation { get; set; }
        public bool L11P1NeedsUpdation { get; set; }
        public bool L12P1NeedsUpdation { get; set; }
        public bool L8P2NeedsUpdation { get; set; }
        public bool L8p3NeedsUpdation { get; set; }
        public string SUPP_CODE { get; set; }
    }
}
